# User config
author: "Hà Ly"
author_full: "Luu Hà Ly"
tagline: "Handmade by a Vietnamese in Slovakia"
description: "Hi! My name is Ly and I am a Vietnamese living in Slovakia. I am a handmade lover and maker. People say that I am amazing 😉"
keywords: "Handmade, Vietnamese, Design, Fashion, Home"
email: "luuhaly90@gmail.com"
instagram: "https://www.instagram.com/luu.ha.ly/"
sashe: "https://www.sashe.sk/ha.ly"

# Site config
baseurl: ""
highlighter: rouge
