# User config
author: "Haly.me"
author_full: "Luu Hà Ly"
tagline: "Handmade by a Vietnamese in Slovakia"
description: "Hi! My name is Ly and I am a Vietnamese living in Slovakia. I am a handmade lover and maker. People say that I am creative and friendly. 😉"
keywords: "Handmade, Vietnamese, Design, Fashion, Home"
email: "luuhaly90@gmail.com"
instagram: "https://www.instagram.com/haly.atelier/"
sashe: "https://www.sashe.sk/ha.ly"

# Site config
baseurl: ""
highlighter: rouge
sass:
    sass_dir: assets/scss
    style: compressed
  
