# User config
author: "Haly.me"
author_full: "Luu Hà Ly"
tagline: "Handmade by a Vietnamese in Slovakia"
description: "Hi! My name is Ly, and I'm a Vietnamese living in Slovakia. People often describe me as friendly and creative. 😉"
keywords: "Handmade, Vietnamese, Design, Fashion, Home"
email: "luuhaly90@gmail.com"
instagram: "https://www.instagram.com/_haly.me_/"
sashe: "https://www.sashe.sk/ha.ly"

# Site config
baseurl: ""
highlighter: rouge
sass:
    sass_dir: assets/scss
    style: compressed
  
